export interface BingoPreset {
  name: string
  items: string[]
}

export const PRESETS: Record<string, BingoPreset> = {
  generic: {
    name: 'Generic Conference',
    items: [
      "Someone says 'synergy'",
      "'Let's take this offline'",
      "'Can you see the back row?'",
      "'In the interest of time...'",
      "'Circling back to...'",
      "'Unprecedented times'",
      "'Paradigm shift'",
      "'Can everyone hear me?'",
      "'Great question!'",
      "'AI' mentioned in every talk",
      "'Moving forward...'",
      "'Low-hanging fruit'",
      "'Unpack that'",
      "'Deep dive'",
      "'Pivot'",
      "'Ecosystem'",
      "'Stakeholders'",
      "'Best practices'",
      "'Disruptive'",
      "'Scalable'",
      "'Actionable insights'",
      "'Touch base'",
      "'Circle back'",
      "'Game changer'",
      "'Value proposition'",
      "'It's on the next slide'",
      "'I'll keep this brief'",
      "'Sorry, wrong slide'",
      "'Bear with me'",
      "'As I was saying...'",
      "'To be fair...'",
      'Speaker goes over time',
      "Laptop won't connect to projector",
      'Death by PowerPoint',
      "Speaker says 'next slide please'",
      'Gratuitous stock photos in slides',
      'Presenter reads slides word for word',
      'A talk starts with a meme',
      'Abstract unrelated to the talk',
      'Overly long introductions',
      'Sponsored talk disguised as science',
      "Video won't play",
      'Slide has a typo',
      'Wrong aspect ratio on slides',
      'Laser pointer circles aimlessly',
      'Speaker faces the screen not the audience',
      'Slides in Comic Sans',
      'Chart with no axis labels',
      'Pie chart with too many slices',
      'Screenshot of a spreadsheet',
      "Slide still has 'Click to add title'",
      'Watermark on stock image',
      'Speaker skips 10 slides',
      'Animations on every slide',
      'Presenter uses their phone as notes',
      'Awkward Q&A silence',
      "Someone asks a 5-min 'question'",
      'Panel moderator dominates',
      'Question is actually a statement',
      'Same person asks three questions',
      'Question completely off topic',
      'Chair cuts off the Q&A',
      "'More of a comment than a question'",
      'Questioner starts with their own CV',
      "Wi-Fi doesn't work",
      'Free coffee runs out',
      'Fire alarm or evacuation drill',
      'Terrible venue map',
      'Breakout room too small',
      'Microphone feedback screech',
      'Temperature is wrong in the room',
      'Lunch runs out early',
      'Catering only has decaf',
      'No power outlets anywhere',
      'Queue for the bathroom',
      'Lift takes forever',
      'Registration queue chaos',
      'Badge on wrong lanyard colour',
      'Venue has no phone signal',
      'Room change not announced',
      'Projector makes a loud fan noise',
      'Air conditioning too loud',
      'Chair too uncomfortable to sit in',
      "Someone's phone rings",
      'Someone naps in the back row',
      'Someone plugs their startup',
      'Name badge is upside down',
      'Late arrivals during keynote',
      'Twitter/X drama about a talk',
      'Someone live-tweets incorrectly',
      'Elevator pitch in the bathroom line',
      'Networking event open bar',
      'Session chair mispronounces a name',
      'Someone takes a photo of every slide',
      'Loud typing during a talk',
      'Group blocks the hallway',
      'Someone wearing conference merch from last year',
      'Animated LinkedIn post about the event',
      'Selfie with the keynote speaker',
      'Business card exchange',
      'Free swag grab',
      'Vendor booth demo crash',
      'Poster session stampede',
      'Tote bag from a sponsor',
      "Free pen that doesn't work",
      'QR code that leads nowhere',
      "App nobody downloaded",
      'Hashtag misspelled',
    ],
  },
  abphm: {
    name: 'ABPHM 2025',
    items: [
      'Figure with no error bars',
      'Acknowledgements longer than conclusions',
      'Wall of text slide',
      'Font too small to read',
      'AI Generated stock image',
      'Phylogeny with no outgroup',
      'Rooted tree labelled as unrooted',
      'SNP threshold not justified',
      '2 SNPS difference',
      'Bandage assembly graph',
      'FastQC screenshot',
      'QUAST',
      'Microreact',
      'BRIG figure',
      'GrapeTree figure',
      'BEAST used',
      'One Health framework diagram',
      "Moore's law mentioned",
      'AI mentioned',
      '"More of a comment than a question"',
      '"We\'re working on that"',
      '"We used default parameters"',
      '"Democratising genomics"',
      '"We built our own pipeline"',
      'Custom python script',
      'Custom perl script',
      'Rust mentioned',
      'Talk runs over time',
      'Late to lunch',
      'On time to lunch',
      "Video won't play",
      '"Real time"',
      '"Reproducible"',
      '"Reference free"',
      'Well travelled salad',
      'John Snow',
      'Kraken2',
      'Snippy',
      'Snakemake',
      'Nextflow',
      'Prokka',
      'Gubbins',
      'Roary pan-genome',
      'CARD database',
      'SPAdes',
      'Shovill',
      'cgMLST',
      'Minimum spanning tree',
      'Convergent evolution',
      'Horizontal gene transfer',
      'Plasmids!',
      'NGS',
      'Long reads',
      'Metagenomics',
      '"Pandemic preparedness"',
      '"Genomic surveillance"',
      'Vibrio cholerae',
      'NDM carbapenemase',
      '"Large language model"',
      '"Deep learning"',
      '"Equity"',
      '"Neglected tropical disease"',
      'AllTheBacteria',
      '"Food-borne pathogen"',
      '"Transmission dynamics"',
      'Outbreak reconstruction',
      '"Low and middle income countries"',
      'ISO accreditation mentioned',
      '"Multi-drug resistant"',
      'Whole genome sequencing',
      '"Bioinformatics pipeline"',
      'Pathogenwatch',
      '"Antimicrobial resistance"',
      '"Global spread"',
      '"Lineage"',
      'Bayesian method',
      '"Transmission event"',
      '"Surveillance"',
      'Pangenome',
      '"Clone"',
    ],
  },
  amr2026: {
    name: 'AMR Genomes 2026',
    items: [
      'AllTheBacteria mentioned',
      '"Genomic surveillance"',
      '"Antimicrobial resistance"',
      'Phage therapy talk',
      '"Big data"',
      'Metagenomics',
      '"One Health"',
      '"Multi-drug resistant"',
      '"Low and middle income countries"',
      'Whole genome sequencing',
      '"Pandemic preparedness"',
      'AI or machine learning mentioned',
      '"Transmission dynamics"',
      'Long reads',
      '"We used default parameters"',
      '"More of a comment than a question"',
      'Talk runs over time',
      'Font too small to read',
      'Wall of text slide',
      "Video won't play",
      'Figure with no error bars',
      'Phylogeny shown',
      'SNP threshold mentioned',
      '"Horizontal gene transfer"',
      'Plasmids!',
      'E. coli mentioned',
      'Klebsiella mentioned',
      'C. difficile mentioned',
      'M. tuberculosis mentioned',
      'Vibrio cholerae mentioned',
      '"Antifungal resistance"',
      'HIV drug resistance',
      'Malaria/Plasmodium mentioned',
      'SubGraphia or CARD database',
      'Nextflow or Snakemake',
      '"Interpretive standards"',
      'ESBL mentioned',
      'Carbapenemase mentioned',
      '"Persistence" or "tolerance"',
      '"Convergent evolution"',
      'Pangenome analysis',
      '"Minimum spanning tree"',
      'Microreact or Pathogenwatch',
      '"Bioinformatics pipeline"',
      '"We built our own pipeline"',
      'Poster pitch under 2 minutes',
      'Poster pitch over time',
      'Late to lunch',
      'On time to lunch',
      'Bar opens mentioned enthusiastically',
      '"Leveraging resistance"',
      '"Antibiotic discovery"',
      'Vaccines for AMR mentioned',
      '"Gut microbiome"',
      '"Growth-arrested bacteria"',
      '"Non-canonical drug escape"',
      '"Nutrient environments"',
      '"Epidemiologically relevant"',
      'TARGet AMR network mentioned',
      '"Spot and Stop Protocol"',
      '"Within-host evolution"',
      '"Between-host spread"',
      'Multi-omic profiling',
      'NGS diagnostics',
      '"Democratising genomics"',
      '"Emerging technologies"',
      'Coach to Heathrow mentioned',
      'Someone asks about reproducibility',
      '"Real time"',
      '"Equity"',
      'Acknowledgements longer than conclusions',
      '"Historical spread"',
      '"Pre- and postantibiotic"',
      'Bayesian method mentioned',
      '"Global spread"',
      'Custom python script',
      '"Community project"',
      '"Infection prevention"',
      'Wellcome logo spotted',
      'Hybrid attendee has audio issues',
      '"Primary care"',
      '"Bloodstream infections"',
      'Age-sex heterogeneity mentioned',
    ],
  },
}

export const PRESET_IDS = Object.keys(PRESETS) as Array<keyof typeof PRESETS>
